COLUMNS:
  make: object 
  model: object
  year: int64  
  mileage: int64  
  engine_hp: int64  
  transmission: object 
  fuel_type: object
  drivetrain: object
  body_type: object
  exterior_color: object
  interior_color: object
  owner_count: int64
  accident_history: object
  seller_type: object
  condition: object 
  trim: object
  vehicle_age: int64
  mileage_per_year: float64
  brand_popularity: float64
  price: float64

TARGET_COLUMN:  
  name: price


numerical_features:
  - year 
  - mileage  
  - engine_hp
  - owner_count
  - vehicle_age
  - mileage_per_year
  - brand_popularity

categorical_features:
  - make 
  - model
  - transmission 
  - fuel_type
  - drivetrain
  - body_type
  - exterior_color
  - interior_color
  - accident_history
  - seller_type
  - condition 
  - trim

drop_columns:
  - accident_history
  - engine_hp

outlier_features:
  - mileage
  - mileage_per_year

target_column: Cost



