dataStore_root: dataStore

data_ingestion:
  root_dir: dataStore/data_ingestion
  #source_url: https://github.com/adyaan1989/datasetsforProjects/raw/master/winequality.zip
  source_url: https://github.com/adyaan1989/datasets/raw/master/vehicle_sales.zip
  local_data_file: dataStore/data_ingestion/data.zip
  unzip_dir: dataStore/data_ingestion

# data validation root
data_validation:
  root_dir: dataStore/data_validation
  unzip_data_dir: dataStore/data_ingestion/vehicle_sales.csv
  STATUS_FILE: dataStore/data_validation/status.txt

# data transformation
data_transformation:
  root_dir: dataStore/data_transformation
  data_path: dataStore/data_ingestion/vehicle_sales.csv
  
# model trainer path
model_trainer:
  root_dir: dataStore/model_trainer
  x_train_data_path: dataStore/data_transformation/X_train.csv
  y_train_data_path: dataStore/data_transformation/y_train.csv
  model_name: model.joblib

### Model evaluation path
model_evaluation:
  root_dir: dataStore/model_evaluation
  x_test_data_path: dataStore/data_transformation/X_test.csv
  y_test_data_path: dataStore/data_transformation/y_test.csv
  model_path: dataStore/model_trainer/model.joblib
  metric_file_name: dataStore/model_evaluation/metrics.json


